### ISSUE TITLE
Write Movement Launchfiles

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#12]
Launchfiles need to be written for launching up our nodes. This task is to write several launchfiles that will launch the corresponding nodes, and load the necessary settings files.
- [x] movement.launch
  - thruster node
  - control node
  - imu node 
  - depth node 
- [x] joystick.launch
  - joystick node
  - joystick_control node
- [x] joystick_control.launch
  - movement.launch
  - joystick.launch

**Comment by bkallaher** [comment]
Some helpful links:
- http://wiki.ros.org/roslaunch/XML
- https://www.clearpathrobotics.com/assets/guides/ros/Launch%20Files.html
- http://wiki.ros.org/roslaunch

**Comment by irwineffect** [comment]
I've created an example launch file for you, take a look at [launch/example.launch](https://github.com/PalouseRobosub/robosub/blob/dev/launch/example.launch)
