### ISSUE TITLE
Control launch file references nonexistent files

### ISSUE THREAD

**Issue by bkallaher** [PalouseRobosub/robosub-2018#121]
The launch file for the control system references a thruster.yaml and control.yaml that don't exist. Update the control launch file to use the cobalt.yaml file that exists.

**Comment by skallaher** [comment]
Is the include folder within launch also outdated? It contains `movement_ironman.xml` and `sensor_ironman.xml`. If so, the movement launch file is outdated, though something should be in place to specify which thrusters to use.

**Comment by skallaher** [comment]
Also, the `sim.launch` file references the unity simulator. This seems like it should also be removed along with any other references to the outdated simulator. Thoughts @BigDCross?

**Comment by dcrossman** [comment]
Yea kill sim.launch.
