### ISSUE TITLE
Repo Cleanup

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub-2018#146]
- [x] Delete SharedImageWriter and SharedImageReader
- [x] Cleanup Launch Files
- [x] Update topic namespaces

**Comment by skallaher** [comment]
Removed SharedImageWriter/Reader and related files in #153.

**Comment by Sindorman** [comment]
- [x] Delete old AI files, and old AI parameter files

**Comment by Sindorman** [comment]
Seems like it has been achieved.

**Comment by Sindorman** [comment]
Seems like this has been achieved
