### ISSUE TITLE
Update Thruster Driver class 

### ISSUE THREAD

**Issue by dcrossman** [PalouseRobosub/robosub-2018#163]
Change the MaestroController class to be the MaestroDriver class.
Update the Maestro class to take in a linearized data from 0-100% force. This class should then take this value and map it to the proper value as specified in the T200 documentation. It should account for deadband and non-linear properties of the thruster.

**Comment by ryan-summers** [comment]
I'll take this. I'm preparing the bluerobotics graphs for regression currently.

**Comment by ryan-summers** [comment]
![thruster_curve_fit](https://cloud.githubusercontent.com/assets/8771450/22211854/5afeb16a-e143-11e6-9499-7f0038ff2955.jpg)
Here's a plot of the cubic exponentials I used for modelling the thruster curves. The key was to ensure that the curve was fit for negative data and positive data separately so that the deadband didn't screw with the fitting.

**Comment by ryan-summers** [comment]
For posterity, I am going to be adding this data and the figures, as well as the python script used to generate the polynomials.
**The following file contains an error in poly_fit.py**
[curve_fitting.zip](https://github.com/PalouseRobosub/robosub/files/724258/curve_fitting.zip)
BlueRobotics data was collected from here: https://plot.ly/create/?fid=rjehangir:103

**Comment by ryan-summers** [comment]
Note that the above curve_fitting.zip file contains an incorrect assumption in the data. Please use the following curve_fitting.zip
[curve_fitting.zip](https://github.com/PalouseRobosub/robosub/files/724635/curve_fitting.zip)
The corrected graph is as follows
![thruster_curve_fit](https://cloud.githubusercontent.com/assets/8771450/22217812/56adedd6-e159-11e6-9da7-9070f1acf787.jpg)

**Comment by irwineffect** [comment]
fixed by #167
