### ISSUE TITLE
BNO055 sometimes does not properly respond on boot

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub-2018#164]
Periodically on power-up, the BNO055 fails to respond properly to the query for the CHIP_ID register. It can be remedied by querying for the CHIP_ID in python using PySerial. Once the CHIP_ID successfully enumerates, the BNO055 will respond properly again. Discover how the fix can be implemented in the C driver.

**Comment by ryan-summers** [comment]
See https://github.com/PalouseRobosub/robosub/pull/196

**Comment by skallaher** [comment]
This should only be closed when the PR is merged.
