### ISSUE TITLE
Create MSP430FR5969 Hardware for RosSerial

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub-2018#17]
Because of the new transition to ROS, we have opened up new opportunities for microcontrollers to behave similarly to ROS nodes. RosSerial provides a simple interface for performing this functionality and will reduce development overhead by removing the need to define custom packet specifications. Instead, the standard ROS serialization of messages can be used for continuity between the different ROS nodes. 

---

The electrical team will have three separate microcontrollers operating as ROS nodes
1. Depth Sensors
2. Pneumatics
3. Power Management

---

Create a hardware class `MSP430Hardware` following the specification for RosSerial as defined [here](http://wiki.ros.org/rosserial_client/Tutorials/Adding%20Support%20for%20New%20Hardware).
Place this hardware class in the directory `src/msp430fr5969/`.

This hardware class will be used as a template parameter and should initialize and transmit messages over UART. All RosSerial devices must use the same UART to be compatible for RosSerial.

Implement the hardware class and verify functionality by testing to see if an MSP430FR5969 development board can communicate to a computer-side ROS application.

**Comment by irwineffect** [comment]
Closing this issue, we're going to use arduino for the time being.
