### ISSUE TITLE
Create Project Code Standards

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#19]
Some documentation on any relevant coding standards, perhaps including things like tabs vs spaces and variable naming.
### Location

This should be on the wiki.
### TODO
- [ ] Variable naming
- [ ] File naming
- [ ] Directory scheme
  - Where to find files for specific uses
- [ ] Whitespace
- [ ] Script tool list/descriptions

**Comment by bkallaher** [comment]
The linter has been implemented so as soon as the current code base gets cleaned up it will more strictly enforced.
