### ISSUE TITLE
Disable control system on startup

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#205]
We want the control system to not publish any thruster messages until a control system message has come through, because it doesn't make any sense for the control system to do stuff if we haven't given it any commands anyways.

Relevant files:
https://github.com/PalouseRobosub/robosub/blob/dev/src/movement/control_system.cpp
https://github.com/PalouseRobosub/robosub/blob/dev/src/movement/control_system.hpp
https://github.com/PalouseRobosub/robosub/blob/dev/src/movement/control.cpp

Veteran coders: don't do this issue, let a new member tackle it.

Psuedocode:
```c
//startup
enabled = false

//when a control message comes in
enabled = true

//thruster message publishing
if(enabled == true)
{
    //publish thruster message
}
```

**Comment by skallaher** [comment]
Completed by #220.
