### ISSUE TITLE
Write Python Control Message Helper Class

### ISSUE THREAD

**Issue by ryan-summers** [PalouseRobosub/robosub-2018#213]
Write a python class for generating control messages. This will have setters for each field in the message as well as for things like dive-relative, etc.

**Comment by bkallaher** [comment]
I have the basics for this complete (see [bkallaher/pycontrol](/palouserobosub/robosub/tree/bkallaher/pycontrol)). The main question now is who should be doing the broadcasting of the message, my class or the AI?

**Comment by bkallaher** [comment]
Do we also want there to be checks for valid inputs inside this class?

**Comment by irwineffect** [comment]
I'm thinking your constructor should take in a publisher object that the AI initializes, and then you can have a `publish()` method that just internally calls `self.pub.publish(self._control_msg)`

What sort of valid input checking are you thinking of? My gut reaction is nah, I wouldn't worry about. We can just keep it simple.

**Comment by irwineffect** [comment]
Oh, also I understand why you put it the class in `src/movement/`, but you need to think about how an AI module is going to import it. ROS can setup your PYTHONPATH so you can just say `import robosub.src.movement.control_wrapper` or something like that, but you need to configure the CMakeLists.txt and maybe the package.xml.

**Comment by bkallaher** [comment]
If you want the publishing to be done by the wrapper would it be better if the wrapper creates the publisher from a passed in topic name? Would you prefer that the class be moved into either the scripts or ai folder? As for input checks I was thinking mostly for the absolute goals that the passed in values are in range (-180 to 180 for rotation and -50 to 50 for linear).

**Comment by irwineffect** [comment]
Actually yeah good idea on creating the publisher yourself with passed in topic name. You can have that be defaulted to `control` so we don't have to worry about it unless we want to override it. Let's just put it in the AI folder for now. Hmm I still think it's fine to not have checks, no reason to over complicate this class for now.

**Comment by bkallaher** [comment]
Fixed by #265
