### ISSUE TITLE
Cleanup Camera Drivers

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#221]
This could end up being an in-depth process and would most likely require adding the drivers to the robosub Debian repository.
- [ ] Investigate modifying the pointgrey camera drivers to remove many of the unnecessary topics published to.
- [ ] Investigate modifying the pointgrey camera drivers to publish standard Image messages rather than WFOV Images.

This would also include general cleanup in the [camera launch file](https://github.com/PalouseRobosub/robosub/blob/dev/launch/cameras.launch).

- [ ] Remove unnecessary independent processing (Lines 21-25 and 42-46)
- [ ] Add bottom facing camera and allow for it to not be present

**Comment by irwineffect** [comment]
For reference, the driver code is here: 
https://github.com/ros-drivers/pointgrey_camera_driver

**Comment by skallaher** [comment]
This is now High Priority as testing camera calibration and stereo vision needs this to be completed.
