### ISSUE TITLE
Add help to keyboard controller

### ISSUE THREAD

**Issue by HMcCullough** [PalouseRobosub/robosub-2018#231]
The keyboard controller currently has no help text.

**Comment by bkallaher** [comment]
The info on the controller is on the controllers wiki page.

**Comment by skallaher** [comment]
Here is the link to the [wiki page](http://robosub.eecs.wsu.edu/wiki/cs/controllers/start) for your reference.

**Comment by Sindorman** [comment]
I have added the help to the keyboard control. Also changed some of the Controls. But I am not very familiar with publishing process.

**Comment by skallaher** [comment]
Fixed by #241
