### ISSUE TITLE
Maestro Thruster Node

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#27]
**Node Name:** thruster
### Inputs

**topic:** thruster    **msg type:**  [robosub/thruster](https://github.com/PalouseRobosub/robosub/blob/dev/msg/thruster.msg)
### Outputs

Serial interface to Maestro motor controller

**Comment by apersonnamedmichelle** [comment]
While changes are being made to the maestro thruster class, is there anything I should do?
