### ISSUE TITLE
Have AI manager surface on death

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#280]

**Comment by bkallaher** [comment]
Requires control system to support a clear goals service. This guarantees that it will be received upon death of the AI manager.

**Comment by bkallaher** [comment]
#282 will help with this

**Comment by skallaher** [comment]
TODO: Add timeout on `wait_for_service` and report when timeout is exceeded.

**Comment by skallaher** [comment]
Outdated and implemented in the new system.
