### ISSUE TITLE
Dataset Sanitation

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#284]
## Background
The vision dataset is suspected to contain incorrect labels. In addition to this, the Navigation Channel was not labeled and needs to be in order to perform that task. Sloth is required to perform this task.

## Action Required
- Analyze completed dataset chunks and verify label names are correct
- Label instances of the Navigation Channel in annotated dataset chunks

## Workflow
Before acquiring a dataset chunk, verify that it is not in progress or been completed. To do so, consult [this spreadsheet](https://docs.google.com/spreadsheets/d/1WgPhQpCrYXIezs8ve8HWdudSd1LJZrOhKOCWl3gGV3k/edit#gid=0). To claim a chunk, place your name in the "Validated By" column. Once you have completed the chunk, upload the validated json file and highlight the initial tagger's name green in the spreadsheet.

**Comment by ryan-summers** [comment]
This has been implemented in vision_dev. There's now a script that allows a user to progress through a dataset and assign a status of 'Good' or 'Bad'. Then, a script can remove tags with a 'bad' label. Datasets are now routinely sanitized.
