### ISSUE TITLE
Darknet node publishing labeled images

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#285]
The darknet node needs to be modified to so that it draws its predictions on the input image and republishes this "labeled image" on another topic (**/pretty/vision**).

**Comment by Sindorman** [comment]
PalouseRobosub/rs_yolo#3 pull request solves it.

**Comment by daymare** [comment]
Right, fixed by Peter and myself a while ago.

**Comment by skallaher** [comment]
This has not been fixed. @daymare, you have not completed the PR for it.

**Comment by skallaher** [comment]
Fixed by PalouseRobosub/rs_yolo#3.
