### ISSUE TITLE
Switch to Using TRAX as Default IMU

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#290]
## Background
The IMU node uses one of the three IMUs onboard as the default. These are `bno055_left`, `bno055_right`, and `trax`. Currently the default value is `bno055_left`.

## Action Required
- Modify the correct parameter file to utilize the trax sensor by default.

## Workflow
Consult @irwineffect about where this is located and create a pull request with the appropriate changes.

**Comment by Sindorman** [comment]
This is very important!!!

**Comment by brennanpeter** [comment]
Please

**Comment by skallaher** [comment]
Fixed by #335
