### ISSUE TITLE
Update Robosub Debian to Depend on SMACH

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#291]
## Background
The new AI architecture will be using smach as the framework for hierarchical state machines. This is currently not a dependency of the Debian package.

## Action Required
- Modify the Debian package to include ros-indigo-smach-ros and ros-indigo-smach-viewer packages as dependencies

## Workflow
Modify the Debian and perform a regression test on a fresh install of mint.

**Comment by irwineffect** [comment]
Done!
