### ISSUE TITLE
Undistortion does not publish compressed images

### ISSUE THREAD

**Issue by Sindorman** [PalouseRobosub/robosub-2018#296]
Camera left and right undirstortion compressed topics do not publish any data.

**Comment by irwineffect** [comment]
To follow up on this, it looks like the topics are getting advertised (e.g. `/camera/left/undistorted/compressed`) however whenever you try to subscribe via the compressed transport it causes the undistortion node to seg fault.

**Comment by ryan-summers** [comment]
This has been rectified by The Purge. https://github.com/PalouseRobosub/robosub/pull/372
