### ISSUE TITLE
Investigate Dynamic Parameters

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#3]
ROS has a framework for dynamically reloading parameters, which would be useful for several nodes on the sub, including tuning PID parameters. This task is to learn how dynamic parameters work and to create an example node demonstrating how to use them. 

Starting point: http://wiki.ros.org/dynamic_reconfigure/Tutorials

**Comment by irwineffect** [comment]
So, I just discovered this: http://wiki.ros.org/roscpp/Overview/Parameter%20Server#Cached_Parameters

Normally, getting a value from the parameter server takes about 2 ms, using the cached version of the call takes about 33us.

We may still want the dynamic reconfigure for the PID, we'll have to see. 

Sean, once you've pushed your example code and are merged into dev we can close out this issue.

**Comment by skallaher** [comment]
@irwineffect, I guess I didn't really clear up what your use case was for these features. I don't understand quite all of the ins and outs of Cached Parameters, but from what I gathered asking @bkallaher, they can't dump to a file which I would think to be useful with pool testing. If you could clarify what you were thinking of using these for, that would be great.

**Comment by irwineffect** [comment]
kk sounds good
