### ISSUE TITLE
Sign Up For Hacktober Fest

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#308]
Just DO IT!!! (Regardless of the T-Shirt quality)

**Comment by skallaher** [comment]
@connor-wool get to work on this!

**Comment by connor-wool** [comment]
I'm signed up, Sean and Timmy should sign up so we can close this!

**Comment by hmmwhatsthisdo** [comment]
I've also signed up - not sure about Tim though.
