### ISSUE TITLE
Enum bugs in localization.cpp

### ISSUE THREAD

**Issue by connor-wool** [PalouseRobosub/robosub-2018#310]
Run tests on the localization.cpp code (and it's related subsystem code) and create bug issues for any crashes / failed initializations / unexpected outputs

**Comment by skallaher** [comment]
@connor-wool, please provide a discription for this issue.

**Comment by connor-wool** [comment]
Moving this to week 10, we can't really enum bugs until we have a testing suite in place.

**Comment by connor-wool** [comment]
Closing, we've moved past this.
