### ISSUE TITLE
Finalize Localization Methods

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#317]
## Background
For the past few weeks, the Curiosity team has been tasked with analyzing the previous localization engine as well as a few alternatives.

## Action Required
- [ ] Decide on a method to localize the sub
- [ ] Analyze the amount of work the old system needs and provide a report on goals in the form of issues.

**Comment by connor-wool** [comment]
From my subjective testing, I haven't been able to make any super great improvements in the accuracy of either the Kalman filter or the particle filter. I'd recommend actually building the testing system first, and then tuning the existing code. In addition, we need to get this code running on the sub as soon as possible in a pool test, and let it try to navigate along some points. We have no idea how this is going to run "real world"

My vote for "decide on a method to localize the sub" is to just leave the existing code for now.

**Comment by connor-wool** [comment]
@skallaher I think this guy is ready to be closed.
