### ISSUE TITLE
Finalize Localization Testing

### ISSUE THREAD

**Issue by skallaher** [PalouseRobosub/robosub-2018#318]
## Background
The localization system will need to be evaluated and validated using testing.

## Action Required
- [ ] Determine a testing methodology using either gtest (C++) or unittest (Python)
- [ ] Design and document a testing suite for the localization system which will minimize bugs and edge case occurrences during real world testing.

**Comment by connor-wool** [comment]
My preference would be to run in gtest (C++) just so that we can stay all in one language. But, if there's strong support for the python option, I'd be fine going with that as well.

**Comment by skallaher** [comment]
Please use the corresponding library for the language you are using.
