### ISSUE TITLE
Control System Derivative Calculations

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#330]
When the control system runs at a significantly faster rate than our orientation sensors, it results in the control system intermittently spitting out zeros for the velocity/derivative, because the calculations run on values that haven't been updated since the last calculation. The control system should be able to gracefully handle this situation by recognizing when the orientation data hasn't changed since the last control update, and use the previous velocity as the current velocity.

**Comment by btmoore** [comment]
Is there a reason that the control system updates more often than your sensors? I would think the best arrangement would just be for the control system to only be triggered to update upon your localization engine updating (ie, your sensor updating.)

**Comment by ryan-summers** [comment]
Closed due to https://github.com/PalouseRobosub/robosub/pull/349
