### ISSUE TITLE
Create Pull Request for MVP Particle Filter Code

### ISSUE THREAD

**Issue by connor-wool** [PalouseRobosub/robosub-2018#358]
Create a pull request that moves the current particle filter code to master

**Comment by hmmwhatsthisdo** [comment]
For reference, the "current particle filter code" is in branch [sean.r.williams/localization/kf_pf_updates](/PalouseRobosub/robosub/tree/sean.r.williams/localization/kf_pf_updates). The branch needs a rebase and PR lodged against `master`, but should be otherwise ready.

**Comment by hmmwhatsthisdo** [comment]
Now that the PR is "made" per-se, I think we can close this.

**Comment by ryan-summers** [comment]
Please keep issues open until the PR is merged in.
