### ISSUE TITLE
Synchronize Jetson and NUC time properly

### ISSUE THREAD

**Issue by Sindorman** [PalouseRobosub/robosub-2018#408]
The `hacky` way to do it is to run `sudo date --set="$(ssh user@cobalt date)"` on Jetson in one of the launch files. But we need a better long term solution, @irwineffect suggests to find solution using either [chrony](https://chrony.tuxfamily.org/) or NTP

**Comment by neprotalis** [comment]
I got them syncd. They are now both in the same time zone.
