### ISSUE TITLE
Control System Plotter

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#42]
We need a tool for visualizing the current state of the control system (PID values, integral windups, goals, goal states, etc). This should be an RQT plugin. Discussion is needed for how to display information and exactly what information needs to be displayed.

**Comment by skallaher** [comment]
Useful links:
http://wiki.ros.org/rqt/Tutorials/Create%20your%20new%20rqt%20plugin
http://wiki.ros.org/rqt/Tutorials/Writing%20a%20C%2B%2B%20Plugin

**Comment by dcrossman** [comment]
Turn into rqt perspective #13

**Comment by irwineffect** [comment]
should be both!

**Comment by bkallaher** [comment]
partially fixed by #183

**Comment by bkallaher** [comment]
Only need the RQt Perspective now
