### ISSUE TITLE
Modify Joystick Reset Action

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#45]
The trigger of the joystick resets the yaw, pitch and roll goals of the submarine, making it go flat. However, resetting the yaw causes it to swerve around so its yaw is zero. We've decided we don't like this behavior, so we're going to eliminate the yaw reset.

**Comment by irwineffect** [comment]
Relevant lines of code: https://github.com/PalouseRobosub/robosub/blob/dev/src/joystick/joystick_control.cpp#L86-L94

**Comment by skallaher** [comment]
@irwineffect This has been merged into dev. Wanted to check with you as this issue looks like it is complete.

**Comment by irwineffect** [comment]
yep yep!
