### ISSUE TITLE
Integrate microcontroller firmware into build system

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#47]
We want to be able to compile the microcontroller code when we compile all our other software. Ideally, it should also be simple to upload the software after compilation if desired.

Possible methods (feel free to explore others):
- [rosserial_arduino cmake integration](http://wiki.ros.org/rosserial_arduino/Tutorials/CMake)
- [platformio](http://platformio.org/)
- [custom use of arduino cmake](http://www.hygy.hu/Tech-blog_m69/Using-arduino-from-command-line-in-Ubuntu-with-cmake_c1)

**Comment by skallaher** [comment]
@irwineffect, is this necessary anymore after #87?

**Comment by irwineffect** [comment]
Yes, we probably will have other microcontroller code for LEDs, pneumatics, depth, etc.

**Comment by ryan-summers** [comment]
PlatformIO has been selected as the defacto tool. Closing for now unless further discussion is warranted.
