### ISSUE TITLE
Write Sensor ROS Nodes Framework

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#6]
Several ROS nodes need to be created that talk to the sensors and reports our current orientation. We will need one node for each of the sensor models we have (see EE team for details). This task is just to create the basic framework of a ROS node for each sensor, specifics will be in a future task.
### Inputs

Serial communication with our sensors. Exact protocol is dependent on the sensor(s) chosen by the electrical team.
### Outputs

**ros topic:** orientation   **msg type**: [geometry_msgs/Quaternion](http://docs.ros.org/api/geometry_msgs/html/msg/Quaternion.html)

**Comment by skallaher** [comment]
Peter,
       Could you elaborate on why you are impeded so that others can give you some assistance.

**Comment by brennanpeter** [comment]
I think I know how to find what types of variables and analyze the data sheet but I have no idea how to code the node in practice. Jame's tutorials helped me understand the conceptual parts of what I need to do but my lack of experience with using ROS, github and c++ has left me pretty lost on how to actually code it
