### ISSUE TITLE
Write Sensor Trim Service

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#8]
When this service is executed, it should take the current pitch, roll, yaw and set them to be the bias values, so that the current pitch, roll, yaw values are read as 0, 0, 0. The BNO055 imu node should implement this service.

**Comment by irwineffect** [comment]
db458f5a61c61a8be7624b0d30bc605373db2075

**Comment by skallaher** [comment]
I am in need of a build test of the BNO arduino code with the added changes to verify that it works as well as some code review on the BNO function calls.

Using "rosservice call /bno_trim_service" should execute the added changes and zero out the BNO.

**Comment by irwineffect** [comment]
We're currently working on integrating the compilation of Arduino code, I'm not a fan of the arduino-cmake system, looking into integrating with platformio.

**Comment by skallaher** [comment]
@irwineffect, I believe this was made obsolete by #87, is this correct?

**Comment by irwineffect** [comment]
@skallaher well, yes and no. No longer needed for the arduino node, but I think the new orientation node should implement this.
@ryan-summers, can we add this feature to our bno055 node? This is for zeroing out tiny offsets in the mounting.

**Comment by ryan-summers** [comment]
Will add in future. Feel free to assign to me.

**Comment by ryan-summers** [comment]
General issue though is that I don't believe quaternion work through subtraction like Euler does.

**Comment by irwineffect** [comment]
Does the BNO have anything built-in?

**Comment by ryan-summers** [comment]
A quaternion is an orientation matrix, so according to the following post they can be added and subtracting by multiplying together (addition) or multiplying by the inverse (subtraction)
http://answers.unity3d.com/questions/130510/add-or-substract-two-quaternionsrotations.html
Aka:
```
Quaternion offsets;
...
Quaternion reading;
Quaternion normalized_reading = reading * offsets.inverse();
```

**Comment by ryan-summers** [comment]
And to answer your question, the BNO does not have anything builtin that I can see.

**Comment by skallaher** [comment]
Completed by #210.
