### ISSUE TITLE
Write UPS ROS Node

### ISSUE THREAD

**Issue by irwineffect** [PalouseRobosub/robosub-2018#9]
A ROS node needs to be created that interfaces with our UPS, and publishes the data over ROS.
### Inputs

Use the NUT UPS driver to interface with our UPS
### Outputs

**ros topic:** power/ups     **msg type**: [sensor_msgs/BatteryState](http://docs.ros.org/api/sensor_msgs/html/msg/BatteryState.html)

Fill out as many fields of the BatteryState message as possible.

**Comment by bkallaher** [comment]
Might consider using the BatteryState message: http://docs.ros.org/api/sensor_msgs/html/msg/BatteryState.html

**Comment by irwineffect** [comment]
Agreed. Issue description updated accordingly

**Comment by skallaher** [comment]
I was thinking about adding in some features similar to what already exists in upsc, upssched and upsmon with ROS integration. I've made an incomplete UML diagram of what I'm sort of thinking.
![upsnodeuml_incomplete](https://cloud.githubusercontent.com/assets/6586913/18463488/6c7a63c4-793f-11e6-8ca3-3fcf73e9f004.PNG)

@irwineffect, any thoughts? The general idea is that the node would be able to not only signal other nodes to shutdown before shutting down the computer, but it would be able to run other types of commands that might be useful to different nodes based upon event occurrences. There are some details that I would need to work out, but my main question is: Is it worth doing and if so is there anything you would add or remove?

**Comment by irwineffect** [comment]
I'll admit I don't really know how to read UML diagrams, let's talk about it in the lab.

**Comment by skallaher** [comment]
For future reference, these are useful links:

[NUT ups.status possible values](http://networkupstools.org/docs/developer-guide.chunked/ar01s04.html)
[NUT variable list](http://networkupstools.org/docs/user-manual.chunked/apcs01.html)
